const wrapper =  document.querySelector(".wrapper"),
qrInput =  wrapper.querySelector(".form input"),
generateBtn =  wrapper.querySelector(".form button"),
qrImg =  wrapper.querySelector(".qr-code img");

generateBtn.addEventListener("click", ()=> {
    let qrValue = qrInput.value;
    if(!qrValue) return; // if the input is empty then return from here
    generateBtn.innerText = "Generating QR Code...";
    //getting a QR Code from user entered value using the qrserver
    //api and passing the api returned img src to qrImg
    qrImg.src = ` https://api.qrserver.com/v1/create-qr-code/?size=170x170&data=${qrValue}`;
    qrImg.addEventListener("load", ()=> { // once QR Code img loaded
        wrapper.classList.add("active");
        generateBtn.innerText = "Generate QR Code";
    });
});

//Getting Code generated by "Enter Key"
qrInput.addEventListener("keydown", (event)=> {
    let qrValue = qrInput.value;
    if(event.keyCode !== 13) return;
    if(!qrValue) return; // if the input is empty then return from here
    generateBtn.innerText = "Generating QR Code...";
    //getting a QR Code from user entered value using the qrserver
    //api and passing the api returned img src to qrImg
    qrImg.src = ` https://api.qrserver.com/v1/create-qr-code/?size=170x170&data=${qrValue}`;
    qrImg.addEventListener("load", ()=> { // once QR Code img loaded
        wrapper.classList.add("active");
        generateBtn.innerText = "Generate QR Code";
    });
});

qrInput.addEventListener("keyup", ()=> {
    if(!qrInput.value) {
        wrapper.classList.remove("active");
    }
});


